# Generated by Django 6.0.5 on 2026-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=100)),
                ('trip_id', models.CharField(max_length=100)),
                ('container_photo', models.ImageField(upload_to='container_photos/')),
                ('er_file', models.FileField(upload_to='er_files/')),
                ('status', models.CharField(default='Trip Started', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
