# Generated by Django 5.2.1 on 2026-05-26 15:20

import trips.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='second_container_photo',
            field=models.ImageField(blank=True, null=True, upload_to='container_photos/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='container_photo',
            field=models.ImageField(upload_to='container_photos/', validators=[trips.validators.validate_container_photo]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='er_file',
            field=models.FileField(upload_to='er_files/', validators=[trips.validators.validate_er_file]),
        ),
    ]
